UnigramDev/Unigram

Unigram/Unigram.Api/Unigram.Api.csproj, Unigram/Unigram/App.xaml, Unigram/Unigram/Common/CommonStyles.xaml, Unigram/Unigram/Controls/DialogListViewItem.xaml, Unigram/Unigram/Controls/DialogListViewItem.xaml.cs, Unigram/Unigram/Controls/TabHeaderStyle.xaml, Unigram/Unigram/Converters/InitialNameStringConverter.cs, Unigram/Unigram/Unigram.csproj, Unigram/Unigram/Views/DialogSharedMediaPage.xaml, Unigram/Unigram/Views/MainPage.xaml
Now using grid of 12px
Fixed inverted glyph on shared media (mea culpa :P)
Other things.
=> New Grid design

Unigram/Unigram/ViewModels/DialogViewModel.Handle.cs, Unigram/Unigram/ViewModels/DialogViewModel.cs, Unigram/Unigram/Views/AboutPage.xaml, Unigram/Unigram/Views/DialogPage.xaml
- Last seen now always updated
- Member Count of groups
- Online count of groups
=> Last seen field with function (members and online count)

Unigram/Unigram/Controls/VoiceButton.cs
due to thrwon exception reported, i have created a fix.
The problem was the initializing in an thread other than the UI thread (this isn't allowed from MS)
=> fixed bare exception from microphone initializing

Unigram/Unigram/Views/SignIn/SignInPasswordPage.xaml, Unigram/Unigram/Views/SignIn/SignInPasswordPage.xaml.cs
=> Can confirm Password at login with enter

README.md
The reddit channel is archived, so nobody can join the discussion anymore :o
=> Update Info about reddit channel (is archived)

CONTRIBUTING.md, README.md
- General revamp of the file.
- Removed clutter (some to be reintegrated in the GH Wiki).
- More details to build section.
- Added tools and SDK requirements section.
- Added CONTRIBUTING.md file with some basic instructions.
- Added License note and copyright as suggested in the official [how to](https://www.gnu.org/licenses/gpl-howto.html).
=> Revamped README

Unigram/Unigram.Tasks/VoIPCallTask.cs
Sorry, I missed this grammatical mistake on my last PR. Apologies, @FrayxRulez.
=> Fixing another grammatical error

Unigram/Unigram/Controls/BubbleListView.cs
Fix a typo that made unigram uncompilable
=> Fix the error on LoadNextSlice

Unigram/Unigram/Controls/Views/SettingsDownloadView.xaml, Unigram/Unigram/Strings/en/Resources.cs, Unigram/Unigram/Strings/en/Resources.resw, Unigram/Unigram/ViewModels/Settings/SettingsDataAndStorageViewModel.cs
NOTE: In addition to localizing the SettingsDownloadView, this also localizes some hard-coded strings in the SettingsDataAndStorageViewModel that I missed initially.
=> [Localization] SettingsDownloadView

Unigram/Unigram/Controls/Views/ProxyView.xaml, Unigram/Unigram/Controls/Views/ProxyView.xaml.cs, Unigram/Unigram/Strings/en/Resources.cs, Unigram/Unigram/Strings/en/Resources.resw
This PR makes the ProxyView localization-ready.
NOTE: ProxyView is the dialog that allows the management of proxy settings for Unigram.
=> [Localization] ProxyView

Unigram/Unigram/ViewModels/DialogSharedMediaViewModel.cs, Unigram/Unigram/Views/DialogSharedMediaPage.xaml, Unigram/Unigram/Views/DialogSharedMediaPage.xaml.cs
TODO: if file doesn't exist on device filesystem, the save task does nothing (without exception, at least it's safe). We need to implement a step where, in this case, Unigram first try to locally download selected file and then it can show save picker.
=>  Added option for SharedFileListViewItem to save file with FileSavePicker 

Unigram/Unigram/Views/ProfilePage.xaml.cs
This follows the change in latest Telegram mobile clients
=> Replace settings icon with edit one in "manage group" section

Unigram/Unigram/Controls/Views/ShareView.xaml
=> Missing tooltips in ShareView.xaml

Unigram/Unigram/Views/Chats/ChatSharedMediaPage.xaml.cs
Fixes #1638, but also simplifies/beautifies the handling of changing selection.
I did not like a direct fix like in https://github.com/hihain/UnigramMobile/commit/70651d563a11c90eaa5f86b1e75f1e2b7f8ee26d, but I pushed a branch. If you prefer that fix over this one, I could change the branch or close this pull request and open a new one for the other option. Or you do a cherry pick. Let me know. :)
=> SharedMedia TopNavView Simplification

CONTRIBUTING.md
Replace broken link with Unigram Insiders group link.
=> Update broken Unigram group link

Unigram/Unigram/ViewModels/Folders/FolderViewModel.cs
=> Return to previous view on confirming folder edit or creation

Unigram/Unigram/Common/FluidGridView.cs, Unigram/Unigram/Views/Popups/StickerSetPopup.xaml
=> Fixes #2131 exception "A cycle occurred while laying out the GUI." when clicking stickers

Unigram/Unigram/Strings/ar/Additional.resw
Add translations in Arabic.
Allowed by [this message](https://t.me/unigraminsiders/338890) in Unigram group.
=> Translate SaveAs, DeletedMessage, CopyImage

Unigram/Unigram/Views/Settings/Phone/SettingsPhoneIntroPage.xaml
Now it respects the maximum width like the other settings page, the text alignment and the background now are the same as username change page
=> Minor visual improvements in phone in SettingsPhoneIntroPage

Unigram/Unigram/Views/Settings/SettingsAppearancePage.xaml
=> Fixed typo

Unigram/Unigram/Views/ProfilePage.xaml.cs
Fixing https://t.me/unigraminsiders/352357
=> Not showing (Start Secret Chat) if deleted account

Unigram/Unigram/Controls/Messages/Content/VoiceNoteContent.xaml, Unigram/Unigram/Controls/Messages/Content/VoiceNoteContent.xaml.cs, Unigram/Unigram/Controls/Messages/MessageBubble.xaml.cs, Unigram/Unigram/Controls/PlaybackHeader.xaml.cs, Unigram/Unigram/Controls/PlaybackSlider.cs, Unigram/Unigram/Views/ChatView.xaml.cs
This pullrequest makes possible to easily identify forwarded messages in messages list.
Also it adds full accessibility support and keyboard controll to the seekbar slider
=> Accessibility fixes

README.md
Perhaps new look is not ideal, but IMO this link should be there
=> Add unirgamdev.github.io to README.md

Documentation/Shortcuts.md
Do we really need classes for tr?
=> Add missing shortcuts to documentation (Spoiler, Change Status)

Telegram/Views/Payments/PaymentCredentialsPopup.xaml
Amex cards can have 4 digits CVV
=> fix CVV MaxLength

README.md
After internal discussions, we agreed on simplifying and updating the Readme to improve its readability
=> Brand new README 🕺
